#############################################################################
# Makefile for building: Bloc2_Exemple
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  Bloc2_Exemple.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Bloc2_Exemple.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -isystem /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/include -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iglm -Iassimp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Bloc2_Exemple1.0.0
DISTDIR = /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/.tmp/Bloc2_Exemple1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libassimp.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libdraco.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libkubazip.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libminizip.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libpoly2tri.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libpolyclipping.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libpugixml.a /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/lib/libz.a /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MyForm.cpp \
		BL2GLWidget.cpp \
		MyGLWidget.cpp \
		model.cpp \
		assimp/Mesh.cpp \
		assimp/ogldev_texture.cpp \
		assimp/ogldev_util.cpp \
		assimp/3rdparty/stb_image.cpp moc_MyForm.cpp \
		moc_BL2GLWidget.cpp \
		moc_MyGLWidget.cpp
OBJECTS       = main.o \
		MyForm.o \
		BL2GLWidget.o \
		MyGLWidget.o \
		model.o \
		Mesh.o \
		ogldev_texture.o \
		ogldev_util.o \
		stb_image.o \
		moc_MyForm.o \
		moc_BL2GLWidget.o \
		moc_MyGLWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Bloc2_Exemple.pro MyForm.h \
		BL2GLWidget.h \
		MyGLWidget.h \
		model.h main.cpp \
		MyForm.cpp \
		BL2GLWidget.cpp \
		MyGLWidget.cpp \
		model.cpp \
		assimp/Mesh.cpp \
		assimp/ogldev_texture.cpp \
		assimp/ogldev_util.cpp \
		assimp/3rdparty/stb_image.cpp
QMAKE_TARGET  = Bloc2_Exemple
DESTDIR       = 
TARGET        = Bloc2_Exemple


first: all
####### Build rules

Bloc2_Exemple: ui_MyForm.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bloc2_Exemple.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Bloc2_Exemple.pro
	$(QMAKE) -o Makefile Bloc2_Exemple.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Bloc2_Exemple.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Bloc2_Exemple.pro

qmake_all: FORCE


all: Makefile Bloc2_Exemple

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MyForm.h BL2GLWidget.h MyGLWidget.h model.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MyForm.cpp BL2GLWidget.cpp MyGLWidget.cpp model.cpp assimp/Mesh.cpp assimp/ogldev_texture.cpp assimp/ogldev_util.cpp assimp/3rdparty/stb_image.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MyForm.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -isystem /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp/include -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MyForm.cpp moc_BL2GLWidget.cpp moc_MyGLWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MyForm.cpp moc_BL2GLWidget.cpp moc_MyGLWidget.cpp
moc_MyForm.cpp: MyForm.h \
		ui_MyForm.h \
		MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/glm -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MyForm.h -o moc_MyForm.cpp

moc_BL2GLWidget.cpp: BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/glm -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include BL2GLWidget.h -o moc_BL2GLWidget.cpp

moc_MyGLWidget.cpp: MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/glm -I/home/magigb/INDI/Projecte/Codi-Esquelet-Bloc2-PR/assimp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MyGLWidget.h -o moc_MyGLWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MyForm.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MyForm.h
ui_MyForm.h: MyForm.ui \
		/usr/lib/qt5/bin/uic \
		MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h
	/usr/lib/qt5/bin/uic MyForm.ui -o ui_MyForm.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MyForm.h \
		ui_MyForm.h \
		MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MyForm.o: MyForm.cpp MyForm.h \
		ui_MyForm.h \
		MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyForm.o MyForm.cpp

BL2GLWidget.o: BL2GLWidget.cpp BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BL2GLWidget.o BL2GLWidget.cpp

MyGLWidget.o: MyGLWidget.cpp MyGLWidget.h \
		model.h \
		BL2GLWidget.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/Mesh.h \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyGLWidget.o MyGLWidget.cpp

model.o: model.cpp model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

Mesh.o: assimp/Mesh.cpp assimp/Mesh.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/simd/neon.h \
		glm/fwd.hpp \
		glm/detail/qualifier.hpp \
		glm/vec2.hpp \
		glm/ext/vector_bool2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/detail/compute_vector_relational.hpp \
		glm/ext/vector_bool2_precision.hpp \
		glm/ext/vector_float2.hpp \
		glm/ext/vector_float2_precision.hpp \
		glm/ext/vector_double2.hpp \
		glm/ext/vector_double2_precision.hpp \
		glm/ext/vector_int2.hpp \
		glm/ext/vector_int2_sized.hpp \
		glm/ext/scalar_int_sized.hpp \
		glm/ext/vector_uint2.hpp \
		glm/ext/vector_uint2_sized.hpp \
		glm/ext/scalar_uint_sized.hpp \
		glm/vec3.hpp \
		glm/ext/vector_bool3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/ext/vector_bool3_precision.hpp \
		glm/ext/vector_float3.hpp \
		glm/ext/vector_float3_precision.hpp \
		glm/ext/vector_double3.hpp \
		glm/ext/vector_double3_precision.hpp \
		glm/ext/vector_int3.hpp \
		glm/ext/vector_int3_sized.hpp \
		glm/ext/vector_uint3.hpp \
		glm/ext/vector_uint3_sized.hpp \
		glm/vec4.hpp \
		glm/ext/vector_bool4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/ext/vector_bool4_precision.hpp \
		glm/ext/vector_float4.hpp \
		glm/ext/vector_float4_precision.hpp \
		glm/ext/vector_double4.hpp \
		glm/ext/vector_double4_precision.hpp \
		glm/ext/vector_int4.hpp \
		glm/ext/vector_int4_sized.hpp \
		glm/ext/vector_uint4.hpp \
		glm/ext/vector_uint4_sized.hpp \
		glm/mat2x2.hpp \
		glm/ext/matrix_double2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/matrix.hpp \
		glm/mat2x3.hpp \
		glm/ext/matrix_double2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/ext/matrix_double2x3_precision.hpp \
		glm/ext/matrix_float2x3.hpp \
		glm/ext/matrix_float2x3_precision.hpp \
		glm/mat2x4.hpp \
		glm/ext/matrix_double2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/ext/matrix_double2x4_precision.hpp \
		glm/ext/matrix_float2x4.hpp \
		glm/ext/matrix_float2x4_precision.hpp \
		glm/mat3x2.hpp \
		glm/ext/matrix_double3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/ext/matrix_double3x2_precision.hpp \
		glm/ext/matrix_float3x2.hpp \
		glm/ext/matrix_float3x2_precision.hpp \
		glm/mat3x3.hpp \
		glm/ext/matrix_double3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/ext/matrix_double3x3_precision.hpp \
		glm/ext/matrix_float3x3.hpp \
		glm/ext/matrix_float3x3_precision.hpp \
		glm/mat3x4.hpp \
		glm/ext/matrix_double3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/ext/matrix_double3x4_precision.hpp \
		glm/ext/matrix_float3x4.hpp \
		glm/ext/matrix_float3x4_precision.hpp \
		glm/mat4x2.hpp \
		glm/ext/matrix_double4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/ext/matrix_double4x2_precision.hpp \
		glm/ext/matrix_float4x2.hpp \
		glm/ext/matrix_float4x2_precision.hpp \
		glm/mat4x3.hpp \
		glm/ext/matrix_double4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/ext/matrix_double4x3_precision.hpp \
		glm/ext/matrix_float4x3.hpp \
		glm/ext/matrix_float4x3_precision.hpp \
		glm/mat4x4.hpp \
		glm/ext/matrix_double4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/ext/matrix_double4x4_precision.hpp \
		glm/ext/matrix_float4x4.hpp \
		glm/ext/matrix_float4x4_precision.hpp \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/common.hpp \
		glm/detail/func_common.inl \
		glm/detail/compute_common.hpp \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/ext/matrix_double2x2_precision.hpp \
		glm/ext/matrix_float2x2.hpp \
		glm/ext/matrix_float2x2_precision.hpp \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/ext/matrix_projection.hpp \
		glm/gtc/constants.hpp \
		glm/ext/scalar_constants.hpp \
		glm/ext/scalar_constants.inl \
		glm/gtc/constants.inl \
		glm/ext/matrix_projection.inl \
		glm/ext/matrix_clip_space.hpp \
		glm/ext/matrix_clip_space.inl \
		glm/ext/matrix_transform.hpp \
		glm/ext/matrix_transform.inl \
		glm/gtc/matrix_transform.inl \
		assimp/include/assimp/Importer.hpp \
		assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o assimp/Mesh.cpp

ogldev_texture.o: assimp/ogldev_texture.cpp assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/ogldev_texture.h \
		assimp/3rdparty/stb_image.h \
		assimp/3rdparty/stb_image_write.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogldev_texture.o assimp/ogldev_texture.cpp

ogldev_util.o: assimp/ogldev_util.cpp assimp/ogldev_util.h \
		assimp/ogldev_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogldev_util.o assimp/ogldev_util.cpp

stb_image.o: assimp/3rdparty/stb_image.cpp assimp/ogldev_util.h \
		assimp/ogldev_types.h \
		assimp/3rdparty/stb_image.h \
		assimp/3rdparty/stb_image_write.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stb_image.o assimp/3rdparty/stb_image.cpp

moc_MyForm.o: moc_MyForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyForm.o moc_MyForm.cpp

moc_BL2GLWidget.o: moc_BL2GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BL2GLWidget.o moc_BL2GLWidget.cpp

moc_MyGLWidget.o: moc_MyGLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyGLWidget.o moc_MyGLWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

